.TH "src/libc-headers/arch-dependent/AVR Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libc-headers/arch-dependent/AVR Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstdarg\&.h\fP"
.br
.RI "AVR type and macros definitions for variadic functions\&. "
.ti -1c
.RI "file \fBstdint\&.h\fP"
.br
.RI "Fixed width integer types for AVR\&. "
.in -1c
