.TH "src/include/Lazuli Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclock_24\&.h\fP"
.br
.RI "24-Hour clock user interface\&. "
.ti -1c
.RI "file \fBcommon\&.h\fP"
.br
.RI "Basic type definitions and useful macros\&. "
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.RI "Include appropriate config file\&. "
.ti -1c
.RI "file \fBconfig_static_analysis\&.h\fP"
.br
.RI "Lazuli configuration file for static analysis\&. "
.ti -1c
.RI "file \fBlazuli\&.h\fP"
.br
.RI "The public API of the Lazuli kernel\&. "
.ti -1c
.RI "file \fBlist\&.h\fP"
.br
.RI "Doubly linked lists interface\&. "
.ti -1c
.RI "file \fBmutex\&.h\fP"
.br
.RI "Mutexes interface\&. "
.ti -1c
.RI "file \fBserial\&.h\fP"
.br
.RI "Serial port configuration interface\&. "
.ti -1c
.RI "file \fBspinlock\&.h\fP"
.br
.RI "Spinlocks interface\&. "
.in -1c
