.TH "src/kern/modules/clock_24 Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern/modules/clock_24 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclock_24\&.c\fP"
.br
.RI "24-Hour clock kernel implementation\&. "
.in -1c
