.TH "src/libc-headers/arch-dependent/x86_64 Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libc-headers/arch-dependent/x86_64 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstdint\&.h\fP"
.br
.RI "Fixed width integer types for x86_64\&. "
.in -1c
