.TH "src/include/Lazuli/sys/arch/AVR Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli/sys/arch/AVR Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.h\fP"
.br
.RI "Interrupt codes of ATmega328P\&. "
.ti -1c
.RI "file \fBregisters\&.h\fP"
.br
.RI "ATmega328P registers\&. "
.ti -1c
.RI "file \fBtimer_counter_0\&.h\fP"
.br
.RI "Interface for Timer/Counter 0 of the ATMega328p\&. "
.ti -1c
.RI "file \fBtimer_counter_1\&.h\fP"
.br
.RI "Interface for Timer/Counter 1 of the ATMega328p\&. "
.ti -1c
.RI "file \fBusart\&.h\fP"
.br
.RI "USART API for the ATmega328P\&. "
.in -1c
