.TH "src/kern Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkernel\&.c\fP"
.br
.RI "Kernel entry point\&. "
.ti -1c
.RI "file \fBlist\&.c\fP"
.br
.RI "Linked lists implementation\&. "
.ti -1c
.RI "file \fBmemory\&.c\fP"
.br
.RI "Kernel memory functions\&. "
.ti -1c
.RI "file \fBscheduler\&.c\fP"
.br
.RI "Lazuli scheduler implementation\&. "
.ti -1c
.RI "file \fBsizeof_types\&.c\fP"
.br
.RI "Sizeof types\&. "
.in -1c
