.TH "src/kern/arch/AVR Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern/arch/AVR Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarch\&.c\fP"
.br
.RI "Hardware specific layer\&. "
.ti -1c
.RI "file \fBavr_arch\&.h\fP"
.br
.RI "Header file specific to the AVR arch module\&. "
.ti -1c
.RI "file \fBtimer_counter_1\&.c\fP"
.br
.RI "ATMega328p Timer/Counter 1 driver\&. "
.in -1c
