.TH "src/include/Lazuli/sys Directory Reference" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli/sys Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclock_24\&.h\fP"
.br
.RI "24-Hour clock kernel interface\&. "
.ti -1c
.RI "file \fBcompiler\&.h\fP"
.br
.RI "Macro aliases on compiler facilities\&. "
.ti -1c
.RI "file \fBkernel\&.h\fP"
.br
.RI "Kernel symbols definition\&. "
.ti -1c
.RI "file \fBlinker\&.h\fP"
.br
.RI "Symbols defined by the linker\&. "
.ti -1c
.RI "file \fBmemory\&.h\fP"
.br
.RI "Memory management API\&. "
.ti -1c
.RI "file \fBprintf\&.h\fP"
.br
.RI "Internal functions needed for \fBprintf()\fP\&. "
.ti -1c
.RI "file \fBscheduler\&.h\fP"
.br
.RI "Lazuli scheduler interface\&. "
.ti -1c
.RI "file \fBtask\&.h\fP"
.br
.RI "Base task definition and context description\&. "
.in -1c
