.TH "_Lz_LinkedListElement" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Lz_LinkedListElement \- Represents an element of a doubly linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB_Lz_LinkedListElement\fP * \fBnext\fP"
.br
.RI "A pointer to the next element in the list\&. "
.ti -1c
.RI "struct \fB_Lz_LinkedListElement\fP * \fBprev\fP"
.br
.RI "A pointer to the previous element in the list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an element of a doubly linked list\&. 
.PP
Definition at line 25 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
