.TH "AllocationMap" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AllocationMap \- Represents a map of the allocated memory regions and useful memory handlers for a task or the kernel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBbaseMem\fP"
.br
.RI "Base address of the memory region\&. "
.ti -1c
.RI "void * \fBbrk\fP"
.br
.RI "Break position, points to the first location beyond the current end of the heap\&. "
.ti -1c
.RI "void * \fBendMem\fP"
.br
.RI "End address of the memory region\&. "
.ti -1c
.RI "\fBAllocationType\fP \fBallocationType\fP"
.br
.RI "The type of allocation used for this map\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a map of the allocated memory regions and useful memory handlers for a task or the kernel\&. 
.PP
Definition at line 33 of file memory\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
