.TH "src/kern/arch/AVR/avr_arch.h" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern/arch/AVR/avr_arch.h \- Header file specific to the AVR arch module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Lazuli/common\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcpu_sleep\fP (void)"
.br
.RI "Put the AVR CPU to sleep according to the sleep settings\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file specific to the AVR arch module\&. 


.PP
\fBCopyright:\fP
.RS 4
2018-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This header file declares all symbol neeed specifically in the AVR arch module, and not declared in <\fBLazuli/sys/arch/arch\&.h\fP>\&. 
.PP
Definition in file \fBavr_arch\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
