.TH "Clock24" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clock24 \- Represents the type used to hold the time\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clock_24\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBhours\fP"
.br
.RI "Hours\&. "
.ti -1c
.RI "\fBuint8_t\fP \fBminutes\fP"
.br
.RI "Minutes\&. "
.ti -1c
.RI "\fBuint8_t\fP \fBseconds\fP"
.br
.RI "Seconds\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the type used to hold the time\&. 
.PP
Definition at line 26 of file clock_24\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
