.TH "src/include/Lazuli/config.h" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli/config.h \- Include appropriate config file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Include appropriate config file\&. 


.PP
\fBCopyright:\fP
.RS 4
2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This header file is just here to include the appropriate config file if we are performing static analysis\&.
.PP
More info in \fBLazuli/config_static_analysis\&.h\fP\&. 
.PP
Definition in file \fBconfig\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
