.TH "IntegerBytes" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntegerBytes \- Union to access individual bytes of an integer value (with a maximum width of 32 bits)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBpointer\fP"
.br
.RI "Holds the pointer value\&. "
.ti -1c
.RI "void(* \fBfunctionPointer\fP )(void)"
.br
.RI "Hold the function pointer value\&. "
.ti -1c
.RI "\fBuint8_t\fP \fBu8Value\fP"
.br
.RI "Holds the 8-bits value\&. "
.ti -1c
.RI "\fBuint16_t\fP \fBu16Value\fP"
.br
.RI "Holds the 16-bits value\&. "
.ti -1c
.RI "\fBuint32_t\fP \fBu32Value\fP"
.br
.RI "Holds the 32-bits value\&. "
.ti -1c
.RI "char \fBbytes\fP [4]"
.br
.RI "Easily access each byte of the value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Union to access individual bytes of an integer value (with a maximum width of 32 bits)\&. 
.PP
Definition at line 64 of file usart\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
