.TH "Lz_LinkedList" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lz_LinkedList \- Represents the main container for doubly linked elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLz_LinkedListElement\fP * \fBfirst\fP"
.br
.RI "A pointer to the first element of the linked list\&. "
.ti -1c
.RI "\fBLz_LinkedListElement\fP * \fBlast\fP"
.br
.RI "A pointer to the last element of the linked list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the main container for doubly linked elements\&. 
.PP
Definition at line 36 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
