.TH "Lz_SerialConfiguration" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lz_SerialConfiguration \- Represents the configuration of a serial interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serial\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBLz_SerialEnableFlags\fP \fBenableFlags\fP"
.br
.RI "The enable/disable Tx/Rx options\&. "
.ti -1c
.RI "enum \fBLz_SerialStopBits\fP \fBstopBits\fP"
.br
.RI "The number of stop bits\&. "
.ti -1c
.RI "enum \fBLz_SerialParityBit\fP \fBparityBit\fP"
.br
.RI "The kind of parity bit\&. "
.ti -1c
.RI "enum \fBLz_SerialSize\fP \fBsize\fP"
.br
.RI "The size of the character\&. "
.ti -1c
.RI "enum \fBLz_SerialSpeed\fP \fBspeed\fP"
.br
.RI "The baud rate\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the configuration of a serial interface\&. 

This configuration applies for both transmission and reception\&. 
.PP
Definition at line 222 of file serial\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
