.TH "src/include/Lazuli/sys/memory.h" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli/sys/memory.h \- Memory management API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Lazuli/common\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBAllocationMap\fP"
.br
.RI "Represents a map of the allocated memory regions and useful memory handlers for a task or the kernel\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAllocationType\fP { \fBALLOC_UNDEFINED\fP, \fBALLOC_INCREMENTAL\fP }
.RI "Defines the kind of allocation for an \fBAllocationMap\fP\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBKIncrementalMalloc\fP (const \fBsize_t\fP size)"
.br
.RI "Allocate memory for kernel objects using incremental method\&. "
.ti -1c
.RI "void \fBMemory_Copy\fP (const void *source, void *destination, const \fBsize_t\fP size)"
.br
.RI "Copy bytes from one location to another in main memory\&. "
.in -1c
.SH "Detailed Description"
.PP 
Memory management API\&. 


.PP
\fBCopyright:\fP
.RS 4
2017-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
Defines base types and operations for memory management\&. 
.PP
Definition in file \fBmemory\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAllocationType\fP"

.PP
Defines the kind of allocation for an \fBAllocationMap\fP\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIALLOC_INCREMENTAL \fP\fP
< Undefined < Incremental 
.PP
Definition at line 24 of file memory\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void* KIncrementalMalloc (const \fBsize_t\fP size)"

.PP
Allocate memory for kernel objects using incremental method\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP The size in bytes to allocate\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A pointer to the allocated region, or NULL if allocation is impossible\&. 
.RE
.PP

.PP
Definition at line 89 of file memory\&.c\&.
.SS "void Memory_Copy (const void * source, void * destination, const \fBsize_t\fP size)"

.PP
Copy bytes from one location to another in main memory\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP A pointer to the source address in RAM\&. 
.br
\fIdestination\fP A pointer to the destination address in RAM\&. 
.br
\fIsize\fP The number of bytes to copy\&. 
.RE
.PP

.PP
Definition at line 95 of file memory\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
