.TH "src/kern/modules/printf/printf.c" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern/modules/printf/printf.c \- printf implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <Lazuli/common\&.h>\fP
.br
\fC#include <Lazuli/config\&.h>\fP
.br
\fC#include <Lazuli/sys/arch/AVR/usart\&.h>\fP
.br
\fC#include <Lazuli/sys/printf\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBprintf\fP (const char *format,\&.\&.\&.)"
.br
.RI "Produce formatted output to the serial line\&. "
.in -1c
.SH "Detailed Description"
.PP 
printf implementation\&. 


.PP
\fBCopyright:\fP
.RS 4
2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file describes the implementation of printf\&. For now it implements a very minimal subset of stdlib's \fBprintf()\fP\&. For now, this module is useless if module SERIAL is not used\&. 
.PP
Definition in file \fBprintf\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int printf (const char * format,  \&.\&.\&.)"

.PP
Produce formatted output to the serial line\&. This function is fully reentrant\&. No locking mechanism is provided\&.
.PP
.SH "Conversion specifiers"
.PP
.PP
The following conversion specifiers are currently allowed:
.PP
\fBd\fP, \fBi\fP The \fIint\fP argument is converted to decimal\&.
.PP
\fBu\fP The \fIunsigned int\fP argument is converted to decimal\&.
.PP
\fB%\fP The character '' is output\&.
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP The format string\&. 
.br
\fI\&.\&.\&.\fP The variadic parameters\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The number of characters output to the serial line, or a negative value if an error occured\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The stack usage of this function is important\&. 
.RE
.PP

.PP
Definition at line 36 of file printf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
