.TH "src/include/Lazuli/sys/arch/AVR/registers.h" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli/sys/arch/AVR/registers.h \- ATmega328P registers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Lazuli/common\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPINB\fP   \fBDIRECT\fP(0x23)"
.br
.RI "Port B Input Pins Address\&. "
.ti -1c
.RI "#define \fBDDRB\fP   \fBDIRECT\fP(0x24)"
.br
.RI "Port B Data Direction Register\&. "
.ti -1c
.RI "#define \fBPORTB\fP   \fBDIRECT\fP(0x25)"
.br
.RI "Port B Data Register\&. "
.ti -1c
.RI "#define \fBPINC\fP   \fBDIRECT\fP(0x26)"
.br
.RI "Port C Input Pins Address\&. "
.ti -1c
.RI "#define \fBDDRC\fP   \fBDIRECT\fP(0x27)"
.br
.RI "Port C Data Direction Register\&. "
.ti -1c
.RI "#define \fBPORTC\fP   \fBDIRECT\fP(0x28)"
.br
.RI "Port C Data Register\&. "
.ti -1c
.RI "#define \fBPIND\fP   \fBDIRECT\fP(0x29)"
.br
.RI "Port D Input Pins Address\&. "
.ti -1c
.RI "#define \fBDDRD\fP   \fBDIRECT\fP(0x2a)"
.br
.RI "Port D Data Direction Register\&. "
.ti -1c
.RI "#define \fBPORTD\fP   \fBDIRECT\fP(0x2b)"
.br
.RI "Port D Data Register\&. "
.ti -1c
.RI "#define \fBEIFR\fP   \fBDIRECT\fP(0x3c)"
.br
.RI "External Interrupt Flag Register\&. "
.ti -1c
.RI "#define \fBEIMSK\fP   \fBDIRECT\fP(0x3d)"
.br
.RI "External Interrupt Mask Register\&. "
.ti -1c
.RI "#define \fBSMCR\fP   \fBDIRECT\fP(0x53)"
.br
.RI "Sleep Mode Control Register\&. "
.ti -1c
.RI "#define \fBMCUCR\fP   \fBDIRECT\fP(0x55)"
.br
.RI "MCU Control Register\&. "
.ti -1c
.RI "#define \fBSP\fP   \fBDIRECT_T\fP(0x5d, void*)"
.br
.RI "Stack Pointer\&. "
.ti -1c
.RI "#define \fBPRR\fP   \fBDIRECT\fP(0x64)"
.br
.RI "Power Reduction Register\&. "
.ti -1c
.RI "#define \fBEICRA\fP   \fBDIRECT\fP(0x69)"
.br
.RI "External Interrupt Control Register A\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBPRR_PRADC\fP = POSITION(0U), \fBPRR_PRUSART0\fP = POSITION(1U), \fBPRR_PRSPI\fP = POSITION(2U), \fBPRR_PRTIM1\fP = POSITION(3U), \fBPRR_PRTIM0\fP = POSITION(5U), \fBPRR_PRTIM2\fP = POSITION(6U), \fBPRR_PRTWI\fP = POSITION(7U) }
.RI "Content of the PRR register\&. ""
.br
.in -1c
.SH "Detailed Description"
.PP 
ATmega328P registers\&. 


.PP
\fBCopyright:\fP
.RS 4
2017-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file contains general registers definitions for the ATmega328P\&. 
.PP
Definition in file \fBregisters\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
Content of the PRR register\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPRR_PRADC \fP\fP
Power Reduction ADC\&. 
.TP
\fB\fIPRR_PRUSART0 \fP\fP
Power Reduction USART0\&. 
.TP
\fB\fIPRR_PRSPI \fP\fP
Power Reduction Serial Peripheral Interface\&. 
.TP
\fB\fIPRR_PRTIM1 \fP\fP
Power Reduction Timer/Counter 1\&. 
.TP
\fB\fIPRR_PRTIM0 \fP\fP
Power Reduction Timer/Counter 0\&. 
.TP
\fB\fIPRR_PRTIM2 \fP\fP
Power Reduction Timer/Counter 2\&. 
.TP
\fB\fIPRR_PRTWI \fP\fP
Power Reduction TWI\&. 
.PP
Definition at line 81 of file registers\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
