.TH "src/include/Lazuli/serial.h" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli/serial.h \- Serial port configuration interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Lazuli/common\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLz_SerialConfiguration\fP"
.br
.RI "Represents the configuration of a serial interface\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLz_SerialEnableFlags\fP { \fBLZ_SERIAL_DISABLE_ALL\fP = 0, \fBLZ_SERIAL_ENABLE_TRANSMIT\fP = POSITION(1U), \fBLZ_SERIAL_ENABLE_RECEIVE\fP = POSITION(2U), \fBLZ_SERIAL_ENABLE_ALL\fP = LZ_SERIAL_ENABLE_RECEIVE | LZ_SERIAL_ENABLE_TRANSMIT }
.RI "Define flags for enabling/disabling serial transmission/reception\&. ""
.br
.ti -1c
.RI "enum \fBLz_SerialStopBits\fP { \fBLZ_SERIAL_STOP_BITS_1\fP, \fBLZ_SERIAL_STOP_BITS_2\fP }
.RI "Define the number of stop bits to use on serial line\&. ""
.br
.ti -1c
.RI "enum \fBLz_SerialParityBit\fP { \fBLZ_SERIAL_PARITY_NONE\fP, \fBLZ_SERIAL_PARITY_EVEN\fP, \fBLZ_SERIAL_PARITY_ODD\fP }
.RI "Define the kind of parity bit to use on serial line\&. ""
.br
.ti -1c
.RI "enum \fBLz_SerialSize\fP { \fBLZ_SERIAL_SIZE_5\fP, \fBLZ_SERIAL_SIZE_6\fP, \fBLZ_SERIAL_SIZE_7\fP, \fBLZ_SERIAL_SIZE_8\fP }
.RI "Define the size of the character used on serial line\&. ""
.br
.ti -1c
.RI "enum \fBLz_SerialSpeed\fP { \fBLZ_SERIAL_SPEED_2400\fP, \fBLZ_SERIAL_SPEED_4800\fP, \fBLZ_SERIAL_SPEED_9600\fP, \fBLZ_SERIAL_SPEED_19200\fP }
.RI "Define the baud rate of the serial line\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLz_Serial_GetConfiguration\fP (\fBLz_SerialConfiguration\fP *const serialConfiguration)"
.br
.RI "Retrieve the configuration of the serial line\&. "
.ti -1c
.RI "void \fBLz_Serial_SetConfiguration\fP (\fBLz_SerialConfiguration\fP *const serialConfiguration)"
.br
.RI "Set the configuration of the serial line\&. "
.in -1c
.SH "Detailed Description"
.PP 
Serial port configuration interface\&. 


.PP
\fBCopyright:\fP
.RS 4
2019-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file describes the interface of serial port configuration\&. Serial port means here UART/USART device\&.
.PP
The configuration is the same for input (Receive/Rx) and ouput (Transmit/Tx)\&. 
.PP
Definition in file \fBserial\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLz_SerialEnableFlags\fP"

.PP
Define flags for enabling/disabling serial transmission/reception\&. These flags can be combined using bitwise OR (i\&.e\&. | operator)\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILZ_SERIAL_DISABLE_ALL \fP\fP
Disable both serial transmission and reception\&. 
.TP
\fB\fILZ_SERIAL_ENABLE_TRANSMIT \fP\fP
Enable serial transmission\&. 
.TP
\fB\fILZ_SERIAL_ENABLE_RECEIVE \fP\fP
Enable serial reception\&. 
.TP
\fB\fILZ_SERIAL_ENABLE_ALL \fP\fP
Enable both serial transmission and reception\&. 
.PP
Definition at line 30 of file serial\&.h\&.
.SS "enum \fBLz_SerialStopBits\fP"

.PP
Define the number of stop bits to use on serial line\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILZ_SERIAL_STOP_BITS_1 \fP\fP
Use 1 stop bit\&. 
.TP
\fB\fILZ_SERIAL_STOP_BITS_2 \fP\fP
Use 2 stop bits\&. 
.PP
Definition at line 55 of file serial\&.h\&.
.SS "enum \fBLz_SerialParityBit\fP"

.PP
Define the kind of parity bit to use on serial line\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILZ_SERIAL_PARITY_NONE \fP\fP
Use no parity bit\&. 
.TP
\fB\fILZ_SERIAL_PARITY_EVEN \fP\fP
Use even parity bit\&. 
.TP
\fB\fILZ_SERIAL_PARITY_ODD \fP\fP
Use odd parity bit\&. 
.PP
Definition at line 90 of file serial\&.h\&.
.SS "enum \fBLz_SerialSize\fP"

.PP
Define the size of the character used on serial line\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILZ_SERIAL_SIZE_5 \fP\fP
Use 5-bit character size on serial line\&. 
.TP
\fB\fILZ_SERIAL_SIZE_6 \fP\fP
Use 6-bit character size on serial line\&. 
.TP
\fB\fILZ_SERIAL_SIZE_7 \fP\fP
Use 7-bit character size on serial line\&. 
.TP
\fB\fILZ_SERIAL_SIZE_8 \fP\fP
Use 8-bit character size on serial line\&. 
.PP
Definition at line 130 of file serial\&.h\&.
.SS "enum \fBLz_SerialSpeed\fP"

.PP
Define the baud rate of the serial line\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILZ_SERIAL_SPEED_2400 \fP\fP
Use a 2400 baud rate on the serial line\&. 
.TP
\fB\fILZ_SERIAL_SPEED_4800 \fP\fP
Use a 4800 baud rate on the serial line\&. 
.TP
\fB\fILZ_SERIAL_SPEED_9600 \fP\fP
Use a 9600 baud rate on the serial line\&. 
.TP
\fB\fILZ_SERIAL_SPEED_19200 \fP\fP
Use a 19200 baud rate on the serial line\&. 
.PP
Definition at line 175 of file serial\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void Lz_Serial_GetConfiguration (\fBLz_SerialConfiguration\fP *const serialConfiguration)"

.PP
Retrieve the configuration of the serial line\&. This function will fill the object pointed by the parameter with current serial settings\&.
.PP
\fBParameters:\fP
.RS 4
\fIserialConfiguration\fP A pointer to an allocated \fBLz_SerialConfiguration\fP (e\&.g\&. allocated on the stack)\&. 
.RE
.PP

.PP
Definition at line 20 of file serial\&.c\&.
.SS "void Lz_Serial_SetConfiguration (\fBLz_SerialConfiguration\fP *const serialConfiguration)"

.PP
Set the configuration of the serial line\&. This function will set the different parameters of the serial line according to the configuration pointed by the serialConfiguration parameter\&.
.PP
\fBWarning:\fP
.RS 4
On the AVR platform this function will block interrupts if configuration option LZ_CONFIG_SERIAL_USE_INTERRUPTS is activated\&. On the AVR platform, this function will wait all transmit and receive operations has completed\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIserialConfiguration\fP A pointer to an allocated \fBLz_SerialConfiguration\fP (e\&.g\&. allocated on the stack)\&. 
.RE
.PP

.PP
Definition at line 32 of file serial\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
