.TH "src/kern/modules/serial/serial.c" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern/modules/serial/serial.c \- Serial port configuration implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Lazuli/common\&.h>\fP
.br
\fC#include <Lazuli/config\&.h>\fP
.br
\fC#include <Lazuli/serial\&.h>\fP
.br
\fC#include <Lazuli/sys/arch/arch\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLz_Serial_GetConfiguration\fP (\fBLz_SerialConfiguration\fP *const serialConfiguration)"
.br
.RI "Retrieve the configuration of the serial line\&. "
.ti -1c
.RI "void \fBLz_Serial_SetConfiguration\fP (\fBLz_SerialConfiguration\fP *const serialConfiguration)"
.br
.RI "Set the configuration of the serial line\&. "
.in -1c
.SH "Detailed Description"
.PP 
Serial port configuration implementation\&. 


.PP
\fBCopyright:\fP
.RS 4
2019-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file describes the implementation of serial interface configuration\&. 
.PP
Definition in file \fBserial\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Lz_Serial_GetConfiguration (\fBLz_SerialConfiguration\fP *const serialConfiguration)"

.PP
Retrieve the configuration of the serial line\&. This function will fill the object pointed by the parameter with current serial settings\&.
.PP
\fBParameters:\fP
.RS 4
\fIserialConfiguration\fP A pointer to an allocated \fBLz_SerialConfiguration\fP (e\&.g\&. allocated on the stack)\&. 
.RE
.PP

.PP
Definition at line 20 of file serial\&.c\&.
.SS "void Lz_Serial_SetConfiguration (\fBLz_SerialConfiguration\fP *const serialConfiguration)"

.PP
Set the configuration of the serial line\&. This function will set the different parameters of the serial line according to the configuration pointed by the serialConfiguration parameter\&.
.PP
\fBWarning:\fP
.RS 4
On the AVR platform this function will block interrupts if configuration option LZ_CONFIG_SERIAL_USE_INTERRUPTS is activated\&. On the AVR platform, this function will wait all transmit and receive operations has completed\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIserialConfiguration\fP A pointer to an allocated \fBLz_SerialConfiguration\fP (e\&.g\&. allocated on the stack)\&. 
.RE
.PP

.PP
Definition at line 32 of file serial\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
