.TH "src/kern/sizeof_types.c" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern/sizeof_types.c \- Sizeof types\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br
\fC#include <Lazuli/clock_24\&.h>\fP
.br
\fC#include <Lazuli/common\&.h>\fP
.br
\fC#include <Lazuli/lazuli\&.h>\fP
.br
\fC#include <Lazuli/mutex\&.h>\fP
.br
\fC#include <Lazuli/spinlock\&.h>\fP
.br
\fC#include <Lazuli/sys/scheduler\&.h>\fP
.br
\fC#include <Lazuli/sys/task\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZEOF_TYPE\fP(T,  M)"
.br
.RI "Declare a constant containing the size of a given type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Sizeof types\&. 


.PP
\fBCopyright:\fP
.RS 4
2018-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file is used to retrieve the size of various types in the kernel after compilation\&. The resulting object file (\&.o) of this C file is excluded from linking into the final binary image\&. 
.PP
Definition in file \fBsizeof_types\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIZEOF_TYPE(T, M)"
\fBValue:\fP
.PP
.nf
const volatile size_t                          \
  __sizeof_##T = sizeof(T);                      \
  const volatile char *                          \
  __message_##T = M
.fi
.PP
Declare a constant containing the size of a given type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIT\fP The type of which to get the size\&. 
.br
\fIM\fP An short informative message to display what this type size means\&. 
.RE
.PP

.PP
Definition at line 33 of file sizeof_types\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
