.TH "src/kern/modules/spinlock/spinlock.c" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kern/modules/spinlock/spinlock.c \- Spinlocks implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Lazuli/common\&.h>\fP
.br
\fC#include <Lazuli/config\&.h>\fP
.br
\fC#include <Lazuli/spinlock\&.h>\fP
.br
\fC#include <Lazuli/sys/task\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLz_Spinlock_Unlock\fP (\fBLz_Spinlock\fP *const spinlock)"
.br
.RI "Unset the lock and leave region\&. "
.in -1c
.SH "Detailed Description"
.PP 
Spinlocks implementation\&. 


.PP
\fBCopyright:\fP
.RS 4
2019-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file describes the C part of the implementation of spinlocks\&. 
.PP
Definition in file \fBspinlock\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Lz_Spinlock_Unlock (\fBLz_Spinlock\fP *const spinlock)"

.PP
Unset the lock and leave region\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspinlock\fP A pointer to a Lz_Spinlock used to hold the lock\&.
.RE
.PP
\fBNote:\fP
.RS 4
The calling task will abort if configuration macro LZ_CONFIG_CHECK_NULL_PARAMETERS_IN_SPINLOCKS is set to 1 and the parameter \fCspinlock\fP is \fINULL\fP\&. 
.RE
.PP

.PP
Definition at line 20 of file spinlock\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
