.TH "src/libc-headers/arch-dependent/AVR/stdarg.h" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libc-headers/arch-dependent/AVR/stdarg.h \- AVR type and macros definitions for variadic functions\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
AVR type and macros definitions for variadic functions\&. 


.PP
\fBCopyright:\fP
.RS 4
2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file defines types and macro to support variadic functions on the AVR architecture\&. 
.PP
Definition in file \fBstdarg\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
