.TH "TaskContextLayout" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskContextLayout \- Represents the layout of the stack when saving the context of a task\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile \fBuint8_t\fP \fBsreg\fP"
.br
.RI "State register\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr0\fP"
.br
.RI "Register 0\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr1\fP"
.br
.RI "Register 1\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr2\fP"
.br
.RI "Register 2\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr3\fP"
.br
.RI "Register 3\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr4\fP"
.br
.RI "Register 4\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr5\fP"
.br
.RI "Register 5\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr6\fP"
.br
.RI "Register 6\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr7\fP"
.br
.RI "Register 7\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr8\fP"
.br
.RI "Register 8\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr9\fP"
.br
.RI "Register 9\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr10\fP"
.br
.RI "Register 10\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr11\fP"
.br
.RI "Register 11\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr12\fP"
.br
.RI "Register 12\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr13\fP"
.br
.RI "Register 13\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr14\fP"
.br
.RI "Register 14\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr15\fP"
.br
.RI "Register 15\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr16\fP"
.br
.RI "Register 16\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr17\fP"
.br
.RI "Register 17\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr18\fP"
.br
.RI "Register 18\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr19\fP"
.br
.RI "Register 19\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr20\fP"
.br
.RI "Register 20\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr21\fP"
.br
.RI "Register 21\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr22\fP"
.br
.RI "Register 22\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr23\fP"
.br
.RI "Register 23\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr24\fP"
.br
.RI "Register 24\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr25\fP"
.br
.RI "Register 25\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr26\fP"
.br
.RI "Register 26\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr27\fP"
.br
.RI "Register 27\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr28\fP"
.br
.RI "Register 28\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr29\fP"
.br
.RI "Register 29\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr30\fP"
.br
.RI "Register 30\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBr31\fP"
.br
.RI "Register 31\&. "
.ti -1c
.RI "volatile \fBFuncVoidVoid\fP \fBpc\fP"
.br
.RI "Program counter for the task\&. "
.ti -1c
.RI "volatile \fBFuncVoidVoid\fP \fBterminationCallback\fP"
.br
.RI "Callback to the scheduler to manage task termination\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the layout of the stack when saving the context of a task\&. 

The context of a task consists in saving all of the registers and the program counter\&.
.PP
\fBWarning:\fP
.RS 4
This in fact is a mixed representation of the original layout of the task and the saved layout of the task\&. 
.br
 In the original layout (when the task is allocated) we are not interested in the registers\&. And in the saved layout (when the context is saved, e\&.g\&. preemption) we are not interested in the termination callback\&. 
.RE
.PP

.PP
Definition at line 218 of file task\&.h\&.
.SH "Field Documentation"
.PP 
.SS "volatile \fBFuncVoidVoid\fP TaskContextLayout::terminationCallback"

.PP
Callback to the scheduler to manage task termination\&. 
.PP
\fBWarning:\fP
.RS 4
This member is valid ONLY at the time when the task is allocated and never used its stack yet\&. 
.RE
.PP

.PP
Definition at line 327 of file task\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
