.TH "src/include/Lazuli/sys/arch/AVR/timer_counter_1.h" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Lazuli/sys/arch/AVR/timer_counter_1.h \- Interface for Timer/Counter 1 of the ATMega328p\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <Lazuli/common\&.h>\fP
.br

.SS "Macros"

.PP
.RI "\fBTimer/Counter 1 registers definitions\&.\fP"
.br
Ordered by address\&. 
.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBTCCR1A\fP   \fBDIRECT\fP(0x80)"
.br
.RI "Timer/Counter1 Control Register A\&. "
.ti -1c
.RI "#define \fBTCCR1B\fP   \fBDIRECT\fP(0x81)"
.br
.RI "Timer/Counter1 Control Register B\&. "
.ti -1c
.RI "#define \fBTCCR1C\fP   \fBDIRECT\fP(0x82)"
.br
.RI "Timer/Counter1 Control Register C\&. "
.ti -1c
.RI "#define \fBTCNT1L\fP   \fBDIRECT\fP(0x84)"
.br
.RI "Timer/Counter1 (Low register) "
.ti -1c
.RI "#define \fBTCNT1H\fP   \fBDIRECT\fP(0x85)"
.br
.RI "Timer/Counter1 (High register) "
.ti -1c
.RI "#define \fBTCNT1\fP   \fBDIRECT_T\fP(0x84, uint16_t)"
.br
.RI "Timer/Counter1 (16-bit register) "
.ti -1c
.RI "#define \fBICR1L\fP   \fBDIRECT\fP(0x86)"
.br
.RI "Input Capture Register 1 (Low register) "
.ti -1c
.RI "#define \fBICR1H\fP   \fBDIRECT\fP(0x87)"
.br
.RI "Input Capture Register 1 (High register) "
.ti -1c
.RI "#define \fBOCR1AL\fP   \fBDIRECT\fP(0x88)"
.br
.RI "Output Compare Register 1 A (Low register) "
.ti -1c
.RI "#define \fBOCR1AH\fP   \fBDIRECT\fP(0x89)"
.br
.RI "Output Compare Register 1 A (High register) "
.ti -1c
.RI "#define \fBOCR1BL\fP   \fBDIRECT\fP(0x8a)"
.br
.RI "Output Compare Register 1 B (Low register) "
.ti -1c
.RI "#define \fBOCR1BH\fP   \fBDIRECT\fP(0x8b)"
.br
.RI "Output Compare Register 1 B (High register) "
.ti -1c
.RI "#define \fBTIMSK1\fP   \fBDIRECT\fP(0x6f)"
.br
.RI "Timer/Counter 1 Interrupt Mask Register\&. "
.ti -1c
.RI "#define \fBTIFR1\fP   \fBDIRECT\fP(0x36)"
.br
.RI "Timer/Counter 1 Interrupt Flag Register\&. "
.in -1c
.in -1c
.SS "Enumerations"

.PP
.RI "\fBTimer/Counter 1 registers content\&.\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "enum { \fBTCCR1A_WGM10\fP = POSITION(0U), \fBTCCR1A_WGM11\fP = POSITION(1U), \fBTCCR1A_COM1B0\fP = POSITION(4U), \fBTCCR1A_COM1B1\fP = POSITION(5U), \fBTCCR1A_COM1A0\fP = POSITION(6U), \fBTCCR1A_COM1A1\fP = POSITION(7U) }
.RI "Content of the TCCR1A register\&. ""
.br
.ti -1c
.RI "enum { \fBTCCR1B_CS10\fP = POSITION(0U), \fBTCCR1B_CS11\fP = POSITION(1U), \fBTCCR1B_CS12\fP = POSITION(2U), \fBTCCR1B_WGM12\fP = POSITION(3U), \fBTCCR1B_WGM13\fP = POSITION(4U), \fBTCCR1B_ICES1\fP = POSITION(6U), \fBTCCR1B_ICNC1\fP = POSITION(7U) }
.RI "Content of the TCCR1B register\&. ""
.br
.ti -1c
.RI "enum { \fBTCCR1C_FOC1B\fP = POSITION(6U), \fBTCCR1C_FOC1A\fP = POSITION(7U) }
.RI "Content of the TCCR1C register\&. ""
.br
.ti -1c
.RI "enum { \fBTIMSK1_TOIE1\fP = POSITION(0U), \fBTIMSK1_OCIE1A\fP = POSITION(1U), \fBTIMSK1_OCIE1B\fP = POSITION(2U), \fBTIMSK1_ICIE1\fP = POSITION(5U) }
.RI "Content of the TIMSK1 register\&. ""
.br
.ti -1c
.RI "enum { \fBTIFR1_TOV1\fP = POSITION(0U), \fBTIFR1_OCF1A\fP = POSITION(1U), \fBTIFR1_OCF1B\fP = POSITION(2U), \fBTIFR1_ICF1\fP = POSITION(5U) }
.RI "Content of the TIFR1 register\&. ""
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Interface for Timer/Counter 1 of the ATMega328p\&. 


.PP
\fBCopyright:\fP
.RS 4
2019-2020, Remi Andruccioli remi.andruccioli@gmail.com
.RE
.PP
This file describes the interface of the driver for the '16-bit timer counter 1' of the ATMega328p\&. 
.PP
Definition in file \fBtimer_counter_1\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
Content of the TCCR1A register\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITCCR1A_WGM10 \fP\fP
Waveform generation mode\&. 
.TP
\fB\fITCCR1A_WGM11 \fP\fP
Waveform generation mode\&. 
.TP
\fB\fITCCR1A_COM1B0 \fP\fP
Compare output mode for Channel B\&. 
.TP
\fB\fITCCR1A_COM1B1 \fP\fP
Compare output mode for Channel B\&. 
.TP
\fB\fITCCR1A_COM1A0 \fP\fP
Compare output mode for Channel A\&. 
.TP
\fB\fITCCR1A_COM1A1 \fP\fP
Compare output mode for Channel A\&. 
.PP
Definition at line 84 of file timer_counter_1\&.h\&.
.SS "anonymous enum"

.PP
Content of the TCCR1B register\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITCCR1B_CS10 \fP\fP
Clock select\&. 
.TP
\fB\fITCCR1B_CS11 \fP\fP
Clock select\&. 
.TP
\fB\fITCCR1B_CS12 \fP\fP
Clock select\&. 
.TP
\fB\fITCCR1B_WGM12 \fP\fP
Waveform generation mode\&. 
.TP
\fB\fITCCR1B_WGM13 \fP\fP
Waveform generation mode\&. 
.TP
\fB\fITCCR1B_ICES1 \fP\fP
Input capture edge select\&. 
.TP
\fB\fITCCR1B_ICNC1 \fP\fP
Input capture noise canceller\&. 
.PP
Definition at line 96 of file timer_counter_1\&.h\&.
.SS "anonymous enum"

.PP
Content of the TCCR1C register\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITCCR1C_FOC1B \fP\fP
Force output compare for channel A\&. 
.TP
\fB\fITCCR1C_FOC1A \fP\fP
Force output compare for channel B\&. 
.PP
Definition at line 109 of file timer_counter_1\&.h\&.
.SS "anonymous enum"

.PP
Content of the TIMSK1 register\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITIMSK1_TOIE1 \fP\fP
Overflow interrupt enable\&. 
.TP
\fB\fITIMSK1_OCIE1A \fP\fP
Output compare A match interrupt enable\&. 
.TP
\fB\fITIMSK1_OCIE1B \fP\fP
Output compare B match interrupt enable\&. 
.TP
\fB\fITIMSK1_ICIE1 \fP\fP
Input capture enable\&. 
.PP
Definition at line 117 of file timer_counter_1\&.h\&.
.SS "anonymous enum"

.PP
Content of the TIFR1 register\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITIFR1_TOV1 \fP\fP
Overflow flag\&. 
.TP
\fB\fITIFR1_OCF1A \fP\fP
Output compare A match flag\&. 
.TP
\fB\fITIFR1_OCF1B \fP\fP
Output compare B match flag\&. 
.TP
\fB\fITIFR1_ICF1 \fP\fP
Input capture flag\&. 
.PP
Definition at line 127 of file timer_counter_1\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
