.TH "Usart" 3 "Sun Sep 6 2020" "Lazuli" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Usart \- Describes the memory mapping for the USART\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usart\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile \fBuint8_t\fP \fBucsr0a\fP"
.br
.RI "USART Control and Status Register A\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBucsr0b\fP"
.br
.RI "USART Control and Status Register B\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBucsr0c\fP"
.br
.RI "USART Control and Status Register C\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fB_reserved\fP"
.br
.RI "Unsed\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBubrr0l\fP"
.br
.RI "USART Baud Rate Register low\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBubrr0h\fP"
.br
.RI "USART Baud Rate Register high\&. "
.ti -1c
.RI "volatile \fBuint8_t\fP \fBudr0\fP"
.br
.RI "USART I/O Data Register\&. "
.in -1c
.SH "Detailed Description"
.PP 
Describes the memory mapping for the USART\&. 
.PP
Definition at line 49 of file usart\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazuli from the source code\&.
